<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
	  <TrimMode>link</TrimMode>
	  <IlcFoldIdenticalMethodBodies>true</IlcFoldIdenticalMethodBodies>
	  <TrimmerDefaultAction>link</TrimmerDefaultAction>
	  <IlcGenerateCompleteTypeMetadata>false</IlcGenerateCompleteTypeMetadata>
	  <IlcGenerateStackTraceData>false</IlcGenerateStackTraceData>
	  <IlcDisableUnhandledExceptionExperience>true</IlcDisableUnhandledExceptionExperience>
	  <ApplicationIcon>Icon.ico</ApplicationIcon>
	  <FileVersion>6.2</FileVersion>
	  <AssemblyName>PopStudio</AssemblyName>
  </PropertyGroup>

    <PropertyGroup>
        <DefineConstants Condition="$(RuntimeIdentifier.Contains('win'))">$(DefineConstants);WINDOWSCONSOLE</DefineConstants>
        <DefineConstants Condition="$(RuntimeIdentifier.Contains('osx'))">$(DefineConstants);MACOSCONSOLE</DefineConstants>
        <DefineConstants Condition="$(RuntimeIdentifier.Contains('linux'))">$(DefineConstants);LINUXCONSOLE</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
        <DefineConstants Condition="$([MSBuild]::IsOSPlatform('Windows'))">$(DefineConstants);WINDOWSCONSOLE</DefineConstants>
        <DefineConstants Condition="$([MSBuild]::IsOSPlatform('OSX'))">$(DefineConstants);MACOSCONSOLE</DefineConstants>
        <DefineConstants Condition="$([MSBuild]::IsOSPlatform('Linux'))">$(DefineConstants);LINUXCONSOLE</DefineConstants>
    </PropertyGroup>

	<ItemGroup>
	  <None Remove="Icon.ico" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="Icon.ico" />
	</ItemGroup>

    <ItemGroup>
        <TrimmerRootAssembly Include="MoonSharp.Interpreter" />
    </ItemGroup>

	<ItemGroup>
		<PackageReference Include="K4os.Compression.LZ4.Streams" Version="1.3.8" />
		<PackageReference Include="LZMA-SDK" Version="22.1.1" />
		<PackageReference Include="MoonSharp" Version="2.0.0" />
		<PackageReference Include="Portable.BouncyCastle" Version="1.9.0" />
		<PackageReference Include="System.Text.Encoding.CodePages" Version="9.0.9" />
        <PackageReference Include="System.Drawing.Common" Version="9.0.9" Condition="$(RuntimeIdentifier.Contains('win'))" />
        <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" Condition="!$(RuntimeIdentifier.Contains('win'))" />
	</ItemGroup>

    <ItemGroup Condition="'$(Configuration)' == 'Debug'">
        <PackageReference Include="System.Drawing.Common" Version="9.0.9" Condition="$([MSBuild]::IsOSPlatform('Windows'))" />
        <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" Condition="!$([MSBuild]::IsOSPlatform('Windows'))" />
    </ItemGroup>

	<Import Project="..\PopStudio.Language\PopStudio.Language.projitems" Label="Shared" />

	<Import Project="..\PopStudio.Shared\PopStudio.projitems" Label="Shared" />

</Project>
